### ISSUE TITLE
pair() throws "None" even there is exception.

### ISSUE THREAD

**Issue by kaxing** [kissiel/bt_helper#11]
(Pdb) p devices[1].pair()
Pairing of Arc Touch Mouse SE device failed. org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
None

**Comment by kissiel** [comment]
Now pairing throws a BtException when the process failed.

See e1ae23177e3295b18121e406726711ba4100a847
